-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 19:10:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rezodb1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rezodb1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rezodb1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rezodb1` ;

-- -----------------------------------------------------
-- Table `rezodb1`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`order_items` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `order_items_order_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `order_items_order_id`),
  INDEX `fk_order_items_order_items1_idx` (`order_items_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_order_items1`
    FOREIGN KEY (`order_items_order_id`)
    REFERENCES `rezodb1`.`order_items` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`employee` (
  `EmpID` INT NOT NULL,
  `EmpName` VARCHAR(60) NOT NULL,
  `EmpAge` INT NOT NULL,
  `EmpDept` VARCHAR(45) NULL DEFAULT NULL,
  `Employeecol` VARCHAR(45) NULL DEFAULT NULL,
  `order_items_order_id` INT NOT NULL,
  PRIMARY KEY (`EmpID`, `order_items_order_id`),
  INDEX `fk_employee_order_items1_idx` (`order_items_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_order_items1`
    FOREIGN KEY (`order_items_order_id`)
    REFERENCES `rezodb1`.`order_items` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`merchants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`merchants` (
  `merchants_id` INT NOT NULL,
  `merchant_name` VARCHAR(45) NOT NULL,
  `admin_id` INT NULL DEFAULT NULL,
  `country_code` INT NULL DEFAULT NULL,
  `created_at` VARCHAR(45) NULL DEFAULT NULL,
  `employee_EmpID` INT NOT NULL,
  PRIMARY KEY (`merchants_id`, `employee_EmpID`),
  INDEX `fk_merchants_employee1_idx` (`employee_EmpID` ASC) VISIBLE,
  CONSTRAINT `fk_merchants_employee1`
    FOREIGN KEY (`employee_EmpID`)
    REFERENCES `rezodb1`.`employee` (`EmpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`offices` (
  `offices_id` INT NOT NULL,
  `code` INT NOT NULL,
  `place` VARCHAR(45) NOT NULL,
  `merchants_merchants_id` INT NOT NULL,
  PRIMARY KEY (`offices_id`, `merchants_merchants_id`),
  INDEX `fk_offices_merchants1_idx` (`merchants_merchants_id` ASC) VISIBLE,
  CONSTRAINT `fk_offices_merchants1`
    FOREIGN KEY (`merchants_merchants_id`)
    REFERENCES `rezodb1`.`merchants` (`merchants_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`countries` (
  `country_code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `continent_name` VARCHAR(45) NOT NULL,
  `offices_offices_id` INT NOT NULL,
  PRIMARY KEY (`country_code`, `offices_offices_id`),
  INDEX `fk_countries_offices1_idx` (`offices_offices_id` ASC) VISIBLE,
  CONSTRAINT `fk_countries_offices1`
    FOREIGN KEY (`offices_offices_id`)
    REFERENCES `rezodb1`.`offices` (`offices_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`department` (
  `DeptID` INT NOT NULL,
  `DeptName` VARCHAR(45) NOT NULL,
  `DeptZone` VARCHAR(45) NOT NULL,
  `countries_country_code` INT NOT NULL,
  PRIMARY KEY (`DeptID`, `countries_country_code`),
  INDEX `fk_department_countries1_idx` (`countries_country_code` ASC) VISIBLE,
  CONSTRAINT `fk_department_countries1`
    FOREIGN KEY (`countries_country_code`)
    REFERENCES `rezodb1`.`countries` (`country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`orders` (
  `orders_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `department_DeptID` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `department_DeptID`),
  INDEX `fk_orders_department1_idx` (`department_DeptID` ASC) VISIBLE,
  CONSTRAINT `fk_orders_department1`
    FOREIGN KEY (`department_DeptID`)
    REFERENCES `rezodb1`.`department` (`DeptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`users` (
  `users_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `date_of_birth` VARCHAR(45) NOT NULL,
  `country_code` INT NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `orders_orders_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `orders_orders_id`),
  INDEX `fk_users_orders1_idx` (`orders_orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_orders1`
    FOREIGN KEY (`orders_orders_id`)
    REFERENCES `rezodb1`.`orders` (`orders_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`administrators` (
  `administrators_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `date_of_birth` VARCHAR(45) NOT NULL,
  `country_code` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `users_users_id` INT NOT NULL,
  `users_users_id1` INT NOT NULL,
  PRIMARY KEY (`administrators_id`, `users_users_id`, `users_users_id1`),
  INDEX `fk_administrators_users_idx` (`users_users_id` ASC) VISIBLE,
  INDEX `fk_administrators_users1_idx` (`users_users_id1` ASC) VISIBLE,
  CONSTRAINT `fk_administrators_users`
    FOREIGN KEY (`users_users_id`)
    REFERENCES `rezodb1`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrators_users1`
    FOREIGN KEY (`users_users_id1`)
    REFERENCES `rezodb1`.`users` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`cities` (
  `cities_id` INT NOT NULL,
  `code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `continent_name` VARCHAR(45) NOT NULL,
  `order_items_order_id` INT NOT NULL,
  `order_items_order_items_order_id` INT NOT NULL,
  PRIMARY KEY (`cities_id`, `order_items_order_id`, `order_items_order_items_order_id`),
  INDEX `fk_cities_order_items1_idx` (`order_items_order_id` ASC, `order_items_order_items_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_cities_order_items1`
    FOREIGN KEY (`order_items_order_id` , `order_items_order_items_order_id`)
    REFERENCES `rezodb1`.`order_items` (`order_id` , `order_items_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`costumers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`costumers` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `country_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`pruducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`pruducts` (
  `products_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `merchants_merchants_id` INT NOT NULL,
  `merchants_employee_EmpID` INT NOT NULL,
  PRIMARY KEY (`products_id`, `merchants_merchants_id`, `merchants_employee_EmpID`),
  INDEX `fk_pruducts_merchants1_idx` (`merchants_merchants_id` ASC, `merchants_employee_EmpID` ASC) VISIBLE,
  CONSTRAINT `fk_pruducts_merchants1`
    FOREIGN KEY (`merchants_merchants_id` , `merchants_employee_EmpID`)
    REFERENCES `rezodb1`.`merchants` (`merchants_id` , `employee_EmpID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rezodb1`.`costumers_has_cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rezodb1`.`costumers_has_cities` (
  `costumers_id` INT NOT NULL,
  `cities_cities_id` INT NOT NULL,
  `cities_order_items_order_id` INT NOT NULL,
  `cities_order_items_order_items_order_id` INT NOT NULL,
  PRIMARY KEY (`costumers_id`, `cities_cities_id`, `cities_order_items_order_id`, `cities_order_items_order_items_order_id`),
  INDEX `fk_costumers_has_cities_cities1_idx` (`cities_cities_id` ASC, `cities_order_items_order_id` ASC, `cities_order_items_order_items_order_id` ASC) VISIBLE,
  INDEX `fk_costumers_has_cities_costumers1_idx` (`costumers_id` ASC) VISIBLE,
  CONSTRAINT `fk_costumers_has_cities_costumers1`
    FOREIGN KEY (`costumers_id`)
    REFERENCES `rezodb1`.`costumers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costumers_has_cities_cities1`
    FOREIGN KEY (`cities_cities_id` , `cities_order_items_order_id` , `cities_order_items_order_items_order_id`)
    REFERENCES `rezodb1`.`cities` (`cities_id` , `order_items_order_id` , `order_items_order_items_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
